version: '2'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
    - .:/usr/app/
    - /usr/app/node_modules
    command: npm run dev
    links:
      - postgres
    environment:
       DATABASE_URL: postgres://todoapp@postgres/todos
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos
